# Generated by Django 6.0.4 on 2026-05-15 05:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.TextField(choices=[('base', 'Base'), ('plus', 'Plus'), ('pro', 'Pro')])),
                ('status', models.TextField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled')])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.TextField(choices=[('base', 'Base'), ('plus', 'Plus'), ('pro', 'Pro')])),
                ('status', models.TextField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenants.tenant')),
            ],
        ),
    ]
