# Generated by Django 6.0.4 on 2026-05-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentsubscription',
            name='created_at',
        ),
        migrations.AddField(
            model_name='currentsubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
