# Generated by Django 6.0.4 on 2026-05-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='set_point',
            field=models.FloatField(default=0.0),
        ),
    ]
