# Generated by Django 6.0.4 on 2026-05-30 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_set_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='set_point',
            new_name='setpoint',
        ),
    ]
