# Generated by Django 6.0.4 on 2026-05-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeeinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.TextField(choices=[('admin', 'Admin'), ('worker', 'Worker'), ('viewer', 'Viewer')], default='viewer'),
        ),
    ]
